apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nuxt-kube
  labels:
    app: nuxt-kube
spec:
  selector:
    matchLabels:
      app: nuxt-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: nuxt-kube
    spec:
      containers:
        - name: nuxt-kube
          image: nnkthai/nuxt-kube:latest
          ports:
            - containerPort: 3000