apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nuxt-kube
  labels:
    app: nuxt-kube
spec:
  selector:
    matchLabels:
      app: nuxt-kube
  replicas: 4
  template:
    metadata:
      labels:
        app: nuxt-kube
    spec:
      containers:
        - name: nuxt-kube
          image: 575551465933.dkr.ecr.ap-southeast-1.amazonaws.com/nuxt-kube:latest
          ports:
            - containerPort: 3000
      # you must create secret name is regcred.
      imagePullSecrets:
        - name: regcred