apiVersion: v1
kind: Service
metadata:
  name: service-nuxt-kube
spec:
  type: NodePort
  selector:
    app: nuxt-kube
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 3000
      nodePort: 30010